### ISSUE TITLE
  Cannot find some dongles

### ISSUE THREAD

**Issue by liberatorcnx** [bg111/asterisk-chan-dongle#207]
Didn't realise there is more than one github for chan_dongle....

I have 2 sites each with a 49 port usb hub and each hub having 40 dongles. The hub appears in lsusb as 7 usb hubs each with 7 ports. Here is the response to lsusb ;
~# lsusb
Bus 002 Device 017: ID 12d1:1446 Huawei Technologies Co., Ltd. E1552/E1800/E173 (HSPA modem)
Bus 002 Device 117: ID 12d1:1436 Huawei Technologies Co., Ltd. E173 3G Modem (modem-mode)
Bus 002 Device 016: ID 12d1:1446 Huawei Technologies Co., Ltd. E1552/E1800/E173 (HSPA modem)
Bus 002 Device 115: ID 12d1:1436 Huawei Technologies Co., Ltd. E173 3G Modem (modem-mode)
Bus 002 Device 015: ID 12d1:1446 Huawei Technologies Co., Ltd. E1552/E1800/E173 (HSPA modem)
Bus 002 Device 021: ID 12d1:1436 Huawei Technologies Co., Ltd. E173 3G Modem (modem-mode)
Bus 002 Device 114: ID 12d1:1436 Huawei Technologies Co., Ltd. E173 3G Modem (modem-mode)
Bus 002 Device 009: ID 1a40:0201 Terminus Technology Inc. FE 2.1 7-port Hub
Bus 002 Device 031: ID 12d1:1446 Huawei Technologies Co., Ltd. E1552/E1800/E173 (HSPA modem)
Bus 002 Device 029: ID 12d1:1446 Huawei Technologies Co., Ltd. E1552/E1800/E173 (HSPA modem)
Bus 002 Device 025: ID 12d1:1436 Huawei Technologies Co., Ltd. E173 3G Modem (modem-mode)
Bus 002 Device 028: ID 12d1:1446 Huawei Technologies Co., Ltd. E1552/E1800/E173 (HSPA modem)
Bus 002 Device 024: ID 12d1:1436 Huawei Technologies Co., Ltd. E173 3G Modem (modem-mode)
Bus 002 Device 027: ID 12d1:1446 Huawei Technologies Co., Ltd. E1552/E1800/E173 (HSPA modem)
Bus 002 Device 032: ID 12d1:1436 Huawei Technologies Co., Ltd. E173 3G Modem (modem-mode)
Bus 002 Device 008: ID 1a40:0201 Terminus Technology Inc. FE 2.1 7-port Hub
Bus 002 Device 044: ID 12d1:1436 Huawei Technologies Co., Ltd. E173 3G Modem (modem-mode)
Bus 002 Device 049: ID 12d1:1446 Huawei Technologies Co., Ltd. E1552/E1800/E173 (HSPA modem)
Bus 002 Device 043: ID 12d1:1436 Huawei Technologies Co., Ltd. E173 3G Modem (modem-mode)
Bus 002 Device 042: ID 12d1:1436 Huawei Technologies Co., Ltd. E173 3G Modem (modem-mode)
Bus 002 Device 048: ID 12d1:1446 Huawei Technologies Co., Ltd. E1552/E1800/E173 (HSPA modem)
Bus 002 Device 050: ID 12d1:1436 Huawei Technologies Co., Ltd. E173 3G Modem (modem-mode)
Bus 002 Device 041: ID 12d1:1436 Huawei Technologies Co., Ltd. E173 3G Modem (modem-mode)
Bus 002 Device 007: ID 1a40:0201 Terminus Technology Inc. FE 2.1 7-port Hub
Bus 002 Device 057: ID 12d1:1446 Huawei Technologies Co., Ltd. E1552/E1800/E173 (HSPA modem)
Bus 002 Device 056: ID 12d1:1446 Huawei Technologies Co., Ltd. E1552/E1800/E173 (HSPA modem)
Bus 002 Device 052: ID 12d1:1436 Huawei Technologies Co., Ltd. E173 3G Modem (modem-mode)
Bus 002 Device 055: ID 12d1:1446 Huawei Technologies Co., Ltd. E1552/E1800/E173 (HSPA modem)
Bus 002 Device 051: ID 12d1:1436 Huawei Technologies Co., Ltd. E173 3G Modem (modem-mode)
Bus 002 Device 054: ID 12d1:1446 Huawei Technologies Co., Ltd. E1552/E1800/E173 (HSPA modem)
Bus 002 Device 058: ID 12d1:1436 Huawei Technologies Co., Ltd. E173 3G Modem (modem-mode)
Bus 002 Device 006: ID 1a40:0201 Terminus Technology Inc. FE 2.1 7-port Hub
Bus 002 Device 060: ID 12d1:1446 Huawei Technologies Co., Ltd. E1552/E1800/E173 (HSPA modem)
Bus 002 Device 116: ID 12d1:1436 Huawei Technologies Co., Ltd. E173 3G Modem (modem-mode)
Bus 002 Device 118: ID 12d1:1446 Huawei Technologies Co., Ltd. E1552/E1800/E173 (HSPA modem)
Bus 002 Device 020: ID 12d1:1446 Huawei Technologies Co., Ltd. E1552/E1800/E173 (HSPA modem)
Bus 002 Device 097: ID 12d1:1446 Huawei Technologies Co., Ltd. E1552/E1800/E173 (HSPA modem)
Bus 002 Device 096: ID 12d1:1436 Huawei Technologies Co., Ltd. E173 3G Modem (modem-mode)
Bus 002 Device 030: ID 12d1:1446 Huawei Technologies Co., Ltd. E1552/E1800/E173 (HSPA modem)
Bus 002 Device 005: ID 1a40:0201 Terminus Technology Inc. FE 2.1 7-port Hub
Bus 002 Device 018: ID 12d1:1436 Huawei Technologies Co., Ltd. E173 3G Modem (modem-mode)
Bus 002 Device 110: ID 12d1:1436 Huawei Technologies Co., Ltd. E173 3G Modem (modem-mode)
Bus 002 Device 098: ID 12d1:1436 Huawei Technologies Co., Ltd. E173 3G Modem (modem-mode)
Bus 002 Device 095: ID 12d1:1436 Huawei Technologies Co., Ltd. E173 3G Modem (modem-mode)
Bus 002 Device 010: ID 12d1:1446 Huawei Technologies Co., Ltd. E1552/E1800/E173 (HSPA modem)
Bus 002 Device 004: ID 1a40:0201 Terminus Technology Inc. FE 2.1 7-port Hub
Bus 002 Device 003: ID 1a40:0201 Terminus Technology Inc. FE 2.1 7-port Hub
Bus 002 Device 002: ID 1a40:0201 Terminus Technology Inc. FE 2.1 7-port Hub
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 008 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 007 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 006 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 005 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 004 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 003 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub

Each dongle is entered in to dongle.conf with only the imei number. Problem is on startup or core reload asterisk only recognises about 50% of the dongles. If I do a usbreset for any of the hubs astersik still only sees around half of the dongles.

Here is a response to 'dongle list devices':

*CLI> dongle show devices
ID Group State RSSI Mode Submode Provider Name Model Firmware IMEI IMSI Number
dongle1 0 Free 23 0 0 Telenor@ E173 11.126.16.04.617 86886xxxxxxxxxx 41406xxxxxxxxxx Unknown
dongle2 0 Not connec 0 0 0 NONE Unknown
dongle3 0 Not connec 0 0 0 NONE Unknown
dongle4 0 Not connec 0 0 0 NONE Unknown
dongle5 0 Not connec 0 0 0 NONE Unknown
dongle6 0 Not connec 0 0 0 NONE Unknown
dongle7 0 Free 25 0 0 Telenor@ E173 11.126.16.04.617 86886xxxxxxxxxx 41406xxxxxxxxxx Unknown
dongle8 0 Free 22 0 0 E173 11.126.16.04.617 86886xxxxxxxxxx 41406xxxxxxxxxx Unknown
dongle9 0 Free 22 0 0 Telenor@ E173 11.126.16.04.617 86886xxxxxxxxxx 41406xxxxxxxxxx Unknown
dongle10 0 Free 20 0 0 Telenor@ E173 11.126.16.04.617 86886xxxxxxxxxx 41406xxxxxxxxxx Unknown
dongle11 0 Free 21 0 0 E173 11.126.16.04.617 86886xxxxxxxxxx 41406xxxxxxxxxx Unknown
dongle12 0 Free 21 0 0 Telenor@ E173 11.126.16.04.617 86886xxxxxxxxxx 41406xxxxxxxxxx Unknown
dongle13 0 Free 19 0 0 E173 11.126.16.04.617 86886xxxxxxxxxx 41406xxxxxxxxxx Unknown
dongle14 0 Free 23 0 0 E173 11.126.16.04.617 86886xxxxxxxxxx 41406xxxxxxxxxx Unknown
dongle15 0 Free 15 0 0 Telenor@ E173 11.126.16.04.617 86886xxxxxxxxxx 41406xxxxxxxxxx Unknown
dongle16 0 Free 19 0 0 Telenor@ E173 11.126.16.04.617 86886xxxxxxxxxx 41406xxxxxxxxxx Unknown
dongle17 0 Not connec 0 0 0 NONE Unknown
dongle18 0 Free 20 0 0 Telenor@ E173 11.126.16.04.617 86886xxxxxxxxxx 41406xxxxxxxxxx Unknown
dongle19 0 Free 19 0 0 Telenor@ E173 11.126.16.04.617 86886xxxxxxxxxx 41406xxxxxxxxxx Unknown
dongle20 0 Free 19 0 0 E173 11.126.16.04.617 86886xxxxxxxxxx 41406xxxxxxxxxx Unknown
dongle21 0 Free 22 0 0 Telenor@ E173 11.126.16.04.617 86886xxxxxxxxxx 41406xxxxxxxxxx Unknown
dongle22 0 Free 21 0 0 Telenor@ E173 11.126.16.04.617 86886xxxxxxxxxx 41406xxxxxxxxxx Unknown
dongle23 0 Free 20 0 0 Telenor@ E173 11.126.16.04.617 86886xxxxxxxxxx 41406xxxxxxxxxx Unknown
dongle24 0 Not connec 0 0 0 NONE Unknown
dongle25 0 Not connec 0 0 0 NONE Unknown
dongle26 0 Free 17 0 0 Telenor@ E173 11.126.16.04.617 86886xxxxxxxxxx 41406xxxxxxxxxx Unknown
dongle27 0 Free 20 0 0 Telenor@ E173 11.126.16.04.617 86886xxxxxxxxxx 41406xxxxxxxxxx Unknown
dongle28 0 Free 20 0 0 Telenor@ E173 11.126.16.04.617 86886xxxxxxxxxx 41406xxxxxxxxxx Unknown
dongle29 0 Free 22 0 0 Telenor@ E173 11.126.16.04.617 86886xxxxxxxxxx 41406xxxxxxxxxx Unknown
dongle30 0 Free 21 0 0 Telenor@ E173 11.126.16.04.617 86886xxxxxxxxxx 41406xxxxxxxxxx Unknown
dongle31 0 Not connec 0 0 0 NONE Unknown
dongle32 0 Free 21 0 0 Telenor@ E173 11.126.16.04.617 86886xxxxxxxxxx 41406xxxxxxxxxx Unknown
dongle33 0 Not connec 0 0 0 NONE Unknown
dongle34 0 Free 0 0 0 Telenor@ E173 11.126.16.04.617 86886xxxxxxxxxx 41406xxxxxxxxxx Unknown
dongle35 0 GSM not re 25 0 0 NONE E173 11.126.16.04.617 86886xxxxxxxxxx 41406xxxxxxxxxx Unknown
dongle36 0 Free 22 0 0 Telenor@ E173 11.126.16.04.617 86886xxxxxxxxxx 41406xxxxxxxxxx Unknown
dongle37 0 Free 25 0 0 Telenor@ E173 11.126.16.04.617 86886xxxxxxxxxx 41406xxxxxxxxxx Unknown
dongle38 0 Free 23 0 0 Telenor@ E173 11.126.16.04.617 86886xxxxxxxxxx 41406xxxxxxxxxx Unknown
dongle39 0 Free 24 0 0 Telenor@ E173 11.126.16.04.617 86886xxxxxxxxxx 41406xxxxxxxxxx Unknown
dongle40 0 Not connec 0 0 0 NONE

This was after 3 reboots. Each reboot seems to result in more dongles connected ???

I also have a constant message in verbose mode like this :

[May 2 19:40:32] ERROR[3580]: at_response.c:119 at_response_ok: [dongle9] Received unexpected 'OK'

So how is 'OK' enexpected? I get this for many dongles...

Maybe nobody tried with so many dongles before and I need to change some things in the source to make this work?

**Comment by liberatorcnx** [comment]
Nobody with a similar problem?  No possible solution?

**Comment by markosjal** [comment]
I have the following models

e173
e153
e303

Each model has various hardware versions. I have tested several versions of firmware on the e173s. I can not get consistent results with e173s 

Here is what I have found in relation to detection by imei:

e303 NEVER will recognize by imei (at least  the hardware versions I have tested)
e173 sometimes is recognized by imei (depends on hardware and/or  firmware version???)
e153 always seems to work with firmware below.

BTW the firmware I had to install in the e303 to get voice said it was e173 firmware installer. A Russian site gave me that version 
E303       firmware vers 21.158.13.00.864

E153 firmware   vers 11.609.18.00.00



I started using all e153s with firmware above on gateways with multiple dongles now for that very reason

Also have you considered that MAYBE you have the USB Bus somewhat overloaded? I have not had good luck with even more than a few dongles on a USB bus things go intermnmeiietnt.

I have two Ubuntu based gateways and several Pi based gateways. I bought expensive hubs to test multiple dongles and got no better results than the cheap ones (forgoing power issues) .

**Comment by OutdoorMe** [comment]
Hello liberatorcnx,

do you have found solution of your problem with the missing dongles after restart?
We have here 3 USB hubs each with 10 ports with 10 modems E1550. 
If we switch off all hubs and after that start one by one we have 30 modems working, BUT if we restart the computer with the USB hubs switched on and connected we have around 8-9 modems missing.

We have the same USB hub Chipset like you:
[root@localhost ~]# lsusb
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 003 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 004 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 005 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 001 Device 035: ID 1a40:0201 Terminus Technology Inc. FE 2.1 7-port Hub
Bus 001 Device 036: ID 14cd:8608 Super Top 
Bus 001 Device 037: ID 12d1:1001 Huawei Technologies Co., Ltd. E169/E620/E800 HSDPA Modem
Bus 001 Device 038: ID 12d1:1001 Huawei Technologies Co., Ltd. E169/E620/E800 HSDPA Modem
Bus 001 Device 039: ID 12d1:1001 Huawei Technologies Co., Ltd. E169/E620/E800 HSDPA Modem
Bus 001 Device 040: ID 12d1:1001 Huawei Technologies Co., Ltd. E169/E620/E800 HSDPA Modem
Bus 001 Device 041: ID 12d1:1001 Huawei Technologies Co., Ltd. E169/E620/E800 HSDPA Modem
Bus 001 Device 042: ID 12d1:1001 Huawei Technologies Co., Ltd. E169/E620/E800 HSDPA Modem
Bus 001 Device 043: ID 12d1:1001 Huawei Technologies Co., Ltd. E169/E620/E800 HSDPA Modem
Bus 001 Device 044: ID 12d1:1001 Huawei Technologies Co., Ltd. E169/E620/E800 HSDPA Modem
Bus 001 Device 045: ID 12d1:1001 Huawei Technologies Co., Ltd. E169/E620/E800 HSDPA Modem
Bus 001 Device 046: ID 12d1:1001 Huawei Technologies Co., Ltd. E169/E620/E800 HSDPA Modem
Bus 001 Device 047: ID 1a40:0201 Terminus Technology Inc. FE 2.1 7-port Hub
Bus 001 Device 048: ID 14cd:8601 Super Top 
Bus 001 Device 049: ID 12d1:1001 Huawei Technologies Co., Ltd. E169/E620/E800 HSDPA Modem
Bus 001 Device 050: ID 12d1:1001 Huawei Technologies Co., Ltd. E169/E620/E800 HSDPA Modem
Bus 001 Device 051: ID 12d1:1001 Huawei Technologies Co., Ltd. E169/E620/E800 HSDPA Modem
Bus 001 Device 052: ID 12d1:1001 Huawei Technologies Co., Ltd. E169/E620/E800 HSDPA Modem
Bus 001 Device 053: ID 12d1:1001 Huawei Technologies Co., Ltd. E169/E620/E800 HSDPA Modem
Bus 001 Device 054: ID 12d1:1001 Huawei Technologies Co., Ltd. E169/E620/E800 HSDPA Modem
Bus 001 Device 055: ID 12d1:1001 Huawei Technologies Co., Ltd. E169/E620/E800 HSDPA Modem
Bus 001 Device 056: ID 12d1:1001 Huawei Technologies Co., Ltd. E169/E620/E800 HSDPA Modem
Bus 001 Device 057: ID 12d1:1001 Huawei Technologies Co., Ltd. E169/E620/E800 HSDPA Modem
Bus 001 Device 058: ID 12d1:1001 Huawei Technologies Co., Ltd. E169/E620/E800 HSDPA Modem
Bus 001 Device 059: ID 1a40:0201 Terminus Technology Inc. FE 2.1 7-port Hub
Bus 001 Device 060: ID 14cd:8601 Super Top 
Bus 001 Device 061: ID 12d1:1001 Huawei Technologies Co., Ltd. E169/E620/E800 HSDPA Modem
Bus 001 Device 062: ID 12d1:1001 Huawei Technologies Co., Ltd. E169/E620/E800 HSDPA Modem
Bus 001 Device 063: ID 12d1:1001 Huawei Technologies Co., Ltd. E169/E620/E800 HSDPA Modem
Bus 001 Device 064: ID 12d1:1001 Huawei Technologies Co., Ltd. E169/E620/E800 HSDPA Modem
Bus 001 Device 065: ID 12d1:1001 Huawei Technologies Co., Ltd. E169/E620/E800 HSDPA Modem
Bus 001 Device 066: ID 12d1:1001 Huawei Technologies Co., Ltd. E169/E620/E800 HSDPA Modem
Bus 001 Device 067: ID 12d1:1001 Huawei Technologies Co., Ltd. E169/E620/E800 HSDPA Modem
Bus 001 Device 068: ID 12d1:1001 Huawei Technologies Co., Ltd. E169/E620/E800 HSDPA Modem
Bus 001 Device 069: ID 12d1:1001 Huawei Technologies Co., Ltd. E169/E620/E800 HSDPA Modem
Bus 001 Device 070: ID 12d1:1001 Huawei Technologies Co., Ltd. E169/E620/E800 HSDPA Modem

The USB Hub is 10 ports but is detected as s 7 port ... maube this have something to do with the problem we have, because after asterisk or chan_dongle restart we have the same number of missing modems (8-9) as this 3 ports per HUB not detected .... Maybe the problem is in the USB HUB?
Something important: we have all modems appearing ONLY if we have commented the IMEI and IMSI

[dongle0]
audio=/dev/ttyUSB1
data=/dev/ttyUSB2
;imei=35344304xxxxxxx 
;imsi=2xxxxxxxxxxxxxxx
exten=01
